import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Monday from '../components/Monday'
import AllUsers from '../components/AllUsers'
import Dashboard from '../components/Dashboard'
import Tuesday from '../components/Tuesday'
import Wednesday from '../components/Wednesday'
import Thursday from '../components/Thursday'
import Friday from '../components/Friday'
import FetchMenu from './FetchMenu'
import datashared from "../usersData/SharedBrainly"
import datamicrosoft from "../usersData/Microsoft"
import datapandatron from "../usersData/Pandatron"


export default function Home({ data,data2,data3,data4,data5,alldata }) {
  const dataShared = datashared
  const dataMicrosoft = datamicrosoft
  const dataPandatron = datapandatron

  return (
    <div >
      <Head>
        <title>Nano Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
      <div>
        <div className='font-bold'>Notes</div>
        <div> Morning session ID: 6200d57014d1b95a4c82dc68</div>
        <div> Evening session ID: 61b65debfe32175adb317233</div>
        <div>Format time data = > 17:00 = > Evening hours = 17, Evening minutes = 0 (NOT 00)</div>

      </div>
      {/*  Banner */}
      <main className='space-y-5 mb-5'>
      <Monday data={data}/>
      <Tuesday data2={data2}/>
      <Wednesday data3={data3}/>
      <Thursday data4={data4}/>
      <Friday data5={data5}/>
      </main>
      <div className='border-t-2 py-2'>
              {/*   
               <FetchMenu dataMicrosoft={dataMicrosoft} dataShared={dataShared} dataPandatron={dataPandatron}/>
      </div>
              */}

      <FetchMenu dataMicrosoft={dataMicrosoft} dataShared={dataShared} dataPandatron={dataPandatron}/>
      </div>

      
      
      {/*
            <AllUsers alldata={alldata}/>
      */}

    </div>
  )
}
export async function getServerSideProps(context) {
  const monday = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=Monday', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const data = await monday.json()
  if (!data) {
    return {
      notFound: true,
    }
  }
  const tuesday = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=Tuesday', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const data2 = await tuesday.json()
  if (!data2) {
    return {
      notFound: true,
    }
  }
  const wednesday = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=Wednesday', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const data3 = await wednesday.json()
  if (!data3) {
    return {
      notFound: true,
    }
  }
  const thursday = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=Thursday', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const data4 = await thursday.json()
  if (!data4) {
    return {
      notFound: true,
    }
  }
  const friday = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=Friday', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })
  const data5 = await friday.json()
  if (!data5) {
    return {
      notFound: true,
    }
  }
  const allusers = await fetch('https://61vqrvqwn3.execute-api.us-east-1.amazonaws.com/staging2?day=AllUsers', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },

  })
  const alldata = await allusers.json()
  if (!data) {
    return {
      notFound: true,
    }
  }
  const auth = await fetch("https://www.fibofy.com/signin/save", {
    "headers": {
      "authorization": "8a4bfadf32bfb287126fd9ef9ebac259ca32f132bd5cb4f8391edf9a69a06758",
      "accept": "application/json, text/javascript, */*; q=0.01",
      "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6",
      "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
      "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"102\", \"Google Chrome\";v=\"102\"",
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": "\"macOS\"",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "x-requested-with": "XMLHttpRequest"
    },
    "referrer": "https://www.fibofy.com/signin/?redir=/panda/admin/",
    "referrerPolicy": "strict-origin-when-cross-origin",
    "body": "username=demo%40fibo.io&password=06b46fd2f43962207e999e889ee6e92ea947cecc5b250831ed1e0c48ffb21c17&password2=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "method": "POST",
    "mode": "cors",
    "credentials": "include"
  });
  console.log("status req auth", auth.ok)

  
 


  
  return {
    props: {
      data,data2,data3,data4,data5,alldata
    }, // will be passed to the page component as props
  }
}


